In [1]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[8]

8

In [27]:
b = np.random.randint(0,50,10)

In [31]:
b[8]

31

In [33]:
b

array([31, 47, 34, 15, 15, 47,  8, 39, 31, 45])

In [35]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
b[1:5]

array([47, 34, 15, 15])

In [39]:
b[0:5]

array([31, 47, 34, 15, 15])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [43]:
b[:6]

array([31, 47, 34, 15, 15, 47])

In [45]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [47]:
b[5:]

array([47,  8, 39, 31, 45])

In [49]:
arr[0:5] = 100

In [51]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [63]:
slice_of_arr = arr[:6]

In [65]:
slice_of_arr[:] = 99

In [67]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy = arr.copy()

In [73]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_copy[:] = 50

In [77]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [97]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[45,50,55],[60,65,70]])

In [99]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [45, 50, 55],
       [60, 65, 70]])

In [91]:
arr_2d[1,1]

25

In [93]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [95]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [109]:
arr_2d[2:4,1:2]

array([[40],
       [50]])

In [111]:
arr = np.arange(1,11)

In [113]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
bool_arr = arr > 5

In [121]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [123]:
arr[arr<5]

array([1, 2, 3, 4])

In [125]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [149]:
arr_2d = np.arange(50).reshape(5,10)

In [151]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [153]:
arr_2d[2:3,1:5]

array([[21, 22, 23, 24]])

In [161]:
arr_2d[3:4,1:5]

array([[31, 32, 33, 34]])

In [163]:
arr_2d[1:2,3:5]

array([[13, 14]])

In [165]:
arr_2d[2:3,3:5]

array([[23, 24]])

In [167]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])